name: hello-world
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '55 3,15 * * *'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
