name: scheduled karate running

on:
#  push:
#     branches: [ "main" ]
#  schedule:
#    - cron: '43 13 * * *'
  workflow_dispatch:

env:
  JAVA_VERSION: 11
  JAVA_DISTRIBUTION: temurin

jobs:
  test-run:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write
      checks: write
      issues: read
      pull-requests: write
    steps:

      - name: GitHub Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
#      - name: Install Chrome
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y google-chrome-stable
#      - name: Install Google Chrome
#        continue-on-error: true
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Run test feature
        if: always()
        id: gradle-unit
        continue-on-error: false
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
             test --tests "TestRunner.run" -DskipTests=false

      - name: Upload gradle build reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/

      - name: Upload karate reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: karate-reports
          path: build/karate-reports/




          
